port: "8000"

db:
  username: "postgres"
  host: "localhost"
  port: "5432"
  dbname: "gotest"
  sslmode: "disable"

jwt:
  accessTokenTTL: 300m
  refreshTokenTTL: 50009m
  salt: "hjqrasfasfajfhajs"
  accessTokenKey: "2178fyw8iuau982io4j"
  refreshTokenKey: "129yfsahu32y46yufsd"
